sudo: required
language: node_js
install:
  - echo "install nothing!"
script:
  - echo "no tests!"
jobs:
  include:
    - stage: publish_containers
      deploy:
        provider: script
        services: docker
        script: bash travis/deploy_ecr.sh frontend
    - # continue publish_conatienrs
      deploy:
        provider: script
        services: docker
        script: bash travis/deploy_ecr.sh api
    - stage: deploy
      deploy:
        provider: elasticbeanstalk
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        app: "tracedemo"
        env: "Tracedemo-env-2"
        bucket: "elasticbeanstalk-us-east-1-151114962295"
        edge: true