sudo: required
language: node_js
env:
- AWS_ACCOUNT=151114962295
services:
- docker
install:
  - echo "install nothing!"
script:
  - echo "no tests!"
jobs:
  include:
    - stage: publish_containers
      before_deploy: cd frontend
      deploy:
        provider: script
        script: bash travis/deploy_ecr.sh tracedemo-frontend
        on:
          branch: docker
    - # continue publish_conatienrs
      before_deploy: cd backend
      deploy:
        provider: script
        script: bash travis/deploy_ecr.sh tracedemo-backend
        on:
          branch: docker
    - stage: deploy
      deploy:
        provider: elasticbeanstalk
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        app: "tracedemo"
        env: "Tracedemo-env-2"
        bucket: "elasticbeanstalk-us-east-1-151114962295"
        edge: true
        on:
          branch: docker