version: '3.2'

services:
  web:
    build: ./frontend
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - web_modules:/usr/src/app/node_modules
  api:
    build: ./backend/api
    command: npm run dev
    ports:
      - 3001:3001
    volumes:
      - ./backend/api:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  web_modules:
