version: '3.2'

services:
  web:
    build: ./frontend
    environment:
      - NODE_ENV=production
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules:
